-- Run in an explicit transaction. Every fixture and mutation is rolled back.
begin;
do $$
declare
  owner uuid; actor uuid; other_actor uuid; reader uuid; job uuid; post uuid;
  result jsonb; again jsonb; did_reject boolean; client text; code text; access text; refresh text;
begin
  select id into owner from auth.users where raw_app_meta_data->>'role'='admin' limit 1;
  if owner is null then raise exception 'No admin owner for test'; end if;
  insert into public.agent_credentials(owner_id,name,scopes,expires_at) values(owner,'transaction test',array['posts:read','posts:write','posts:publish','jobs:write'],now()+interval '1 hour') returning id into actor;
  insert into public.agent_credentials(owner_id,name,scopes,expires_at) values(owner,'second worker test',array['posts:write','posts:publish','jobs:write'],now()+interval '1 hour') returning id into other_actor;
  insert into public.agent_credentials(owner_id,name,scopes,expires_at) values(owner,'draft only test',array['posts:write'],now()+interval '1 hour') returning id into reader;
  result=public.makezaa_agent_mutate(actor::text,'job_create','db-test-job','job-hash',null,'{"prompt":"Database test only","expected_posts":1}',null,null);
  job=(result->>'id')::uuid;
  perform public.makezaa_job_transition(job,actor,'claim','lease-one','{}');
  did_reject=false;
  begin perform public.makezaa_job_transition(job,other_actor,'claim','lease-two','{}'); exception when others then if sqlerrm<>'job_not_available' then raise; end if; did_reject=true; end;
  if not did_reject then raise exception 'Concurrent claim accepted'; end if;
  did_reject=false;
  begin perform public.makezaa_job_transition(job,actor,'progress',null,'{}'); exception when others then if sqlerrm<>'invalid_job_lease' then raise; end if; did_reject=true; end;
  if not did_reject then raise exception 'Null lease accepted'; end if;
  did_reject=false;
  begin perform public.makezaa_job_transition(job,actor,'completed','lease-one','{"summary":"False success"}'); exception when others then if sqlerrm<>'published_post_count_incomplete' then raise; end if; did_reject=true; end;
  if not did_reject then raise exception 'Incomplete batch marked completed'; end if;
  update public.agent_jobs set lease_until=now()-interval '1 second' where id=job;
  perform public.makezaa_job_transition(job,other_actor,'claim','lease-two','{}');
  did_reject=false;
  begin perform public.makezaa_job_transition(job,actor,'progress','lease-one','{}'); exception when others then if sqlerrm<>'invalid_job_lease' then raise; end if; did_reject=true; end;
  if not did_reject then raise exception 'Stale worker accepted'; end if;
  result=public.makezaa_agent_mutate(other_actor::text,'post_save','db-test-post','post-hash',null,jsonb_build_object('title','Temporary test','slug','agent-db-test-'||gen_random_uuid()::text,'content','<p>Test only</p>','published',true),job,'lease-two');
  post=(result->>'id')::uuid;
  again=public.makezaa_agent_mutate(other_actor::text,'post_save','db-test-post','post-hash',null,'{}',job,'lease-two');
  if again->>'id'<>post::text then raise exception 'Retry returned a different post'; end if;
  did_reject=false;
  begin perform public.makezaa_agent_mutate(other_actor::text,'post_save','db-test-post','different-hash',null,'{}',job,'lease-two'); exception when others then if sqlerrm<>'idempotency_key_conflict' then raise; end if; did_reject=true; end;
  if not did_reject then raise exception 'Conflicting retry accepted'; end if;
  did_reject=false;
  begin perform public.makezaa_agent_mutate(reader::text,'post_save','db-test-edit','edit-hash',post,'{"title":"Forbidden edit"}',null,null); exception when others then if sqlerrm<>'publish_permission_required' then raise; end if; did_reject=true; end;
  if not did_reject then raise exception 'Draft key edited a public post'; end if;
  perform public.makezaa_job_transition(job,other_actor,'completed','lease-two','{"summary":"Passed","items":[]}');
  if (select status from public.agent_jobs where id=job)<>'completed' then raise exception 'Valid completion failed'; end if;
  result=public.makezaa_media_reserve(actor::text,'media-key','media-hash','{"path":"temporary-test.png","url":"https://example.com/test.png","alt":"test","provenance":"test"}');
  did_reject=false;
  begin perform public.makezaa_media_reserve(actor::text,'media-key','changed-image','{}'); exception when others then if sqlerrm<>'idempotency_key_conflict' then raise; end if; did_reject=true; end;
  if not did_reject then raise exception 'Image retry conflict accepted'; end if;
  client='test-client-'||gen_random_uuid()::text; code='test-code-'||gen_random_uuid()::text; access='test-access-'||gen_random_uuid()::text; refresh='test-refresh-'||gen_random_uuid()::text;
  perform public.makezaa_oauth_register(client,'Database test',array['https://example.com/callback']);
  insert into public.agent_oauth_codes(hash,client_id,owner_id,scopes,redirect_uri,challenge,resource) values(code,client,owner,array['site:read'],'https://example.com/callback','correct-proof','https://www.makezaa.com/api/mcp');
  did_reject=false;
  begin perform public.makezaa_oauth_exchange('authorization_code',code,client,'https://example.com/callback','wrong-proof','https://www.makezaa.com/api/mcp',access,refresh); exception when others then if sqlerrm<>'invalid_grant' then raise; end if; did_reject=true; end;
  if not did_reject then raise exception 'Wrong PKCE accepted'; end if;
  perform public.makezaa_oauth_exchange('authorization_code',code,client,'https://example.com/callback','correct-proof','https://www.makezaa.com/api/mcp',access,refresh);
  did_reject=false;
  begin perform public.makezaa_oauth_exchange('authorization_code',code,client,'https://example.com/callback','correct-proof','https://www.makezaa.com/api/mcp','reuse-access','reuse-refresh'); exception when others then if sqlerrm<>'invalid_grant' then raise; end if; did_reject=true; end;
  if not did_reject then raise exception 'Authorization code reused'; end if;
  did_reject=false;
  begin perform public.makezaa_oauth_exchange('refresh_token',refresh,client,'','','https://wrong-resource.example','new-access','new-refresh'); exception when others then if sqlerrm<>'invalid_grant' then raise; end if; did_reject=true; end;
  if not did_reject then raise exception 'Wrong token audience accepted'; end if;
  perform public.makezaa_oauth_exchange('refresh_token',refresh,client,'','','https://www.makezaa.com/api/mcp','new-access','new-refresh');
  did_reject=false;
  begin perform public.makezaa_oauth_exchange('refresh_token',refresh,client,'','','https://www.makezaa.com/api/mcp','reuse-access','reuse-refresh'); exception when others then if sqlerrm<>'invalid_grant' then raise; end if; did_reject=true; end;
  if not did_reject then raise exception 'Rotated refresh token reused'; end if;
end $$;
select 'PASS: idempotency, task claims, stale/null leases, batch completion, publish permission, media retry, PKCE, code reuse, refresh rotation and token audience' as result;
rollback;
